name: Deploy Frontend to DigitalOcean

on:
  push:
    branches: [main] # Udløser når der pushes direkte til main-grenen
  pull_request:
    branches: [main] # Udløser når en pull request mod main er færdigbehandlet/fusioneret

jobs:
  deploy:
    runs-on: ubuntu-latest # Typen af runner, der bruges til jobbet.

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checker koden ud til $GITHUB_WORKSPACE, så din workflow kan tilgå den.

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Bruger seneste version af setup-node action
        with:
          node-version: '20.x' # Indstiller Node.js version 20

      - name: Install dependencies
        run: npm install # Installerer afhængigheder defineret i package.json.

      - name: Build the React project
        run: npm run build # Kører byggeskriptet specificeret i package.json.

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }} # SSH privatnøgle gemt i GitHub secrets.

      - name: Sync files to DigitalOcean Droplet using rsync
        run: |
          # Definerer SSH forbindelsesinformation
          SSH_USER="jetty"
          DO_DROPLET_IP=${{ secrets.DO_DROPLET_IP }}
          APP_NAME="loanfinder"
          REMOTE_PATH="/home/jetty/2semDockerSetupRemote/site/$APP_NAME/"

          # Synkroniser byggeoutput til Droplet ved hjælp af rsync
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./dist/ $SSH_USER@$DO_DROPLET_IP:$REMOTE_PATH
